apiVersion: batch/v1
kind: Job
metadata:
  name: http-load-generator
spec:
  parallelism: 3
  completions: 3
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: load-generator
        image: busybox:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Starting HTTP load test against nginx-app..."
          for i in $(seq 1 1000000); do
            wget -q -O - http://nginx-app || true
            if [ $((i % 100)) -eq 0 ]; then
              echo "Sent $i requests to nginx-app"
            fi
          done
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
      restartPolicy: Never 